import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AuthenticatedContext } from '../../common/auth/auth-context';
import { encryptAesGcm } from '../../common/crypto/aes-gcm';

const db = vi.hoisted(() => { const lineFindFirst = vi.fn(); const migrationFindUnique = vi.fn(); const policyFindUnique = vi.fn(); const nodeFindMany = vi.fn(); const nodeUpdateMany = vi.fn(); const migrationCreate = vi.fn(); const lineUpdate = vi.fn(); const projectionCreate = vi.fn().mockResolvedValue({ id: 'projection-1', projectionKey: 'line-1:node-a:v2' }); const migrationNodeUpdate = vi.fn(); const externalJobCreate = vi.fn(); const auditCreate = vi.fn(); const transaction = vi.fn(async (callback: (tx: unknown) => unknown) => callback({ dedicated_lines: { findFirst: lineFindFirst, update: lineUpdate }, dedicated_line_migrations: { findUnique: migrationFindUnique, create: migrationCreate }, line_placement_policies: { findUnique: policyFindUnique }, control_nodes: { findMany: nodeFindMany, updateMany: nodeUpdateMany }, dedicated_line_projections: { create: projectionCreate }, dedicated_line_migration_nodes: { update: migrationNodeUpdate }, external_jobs: { create: externalJobCreate }, audit_logs: { create: auditCreate } })); return { lineFindFirst, migrationFindUnique, policyFindUnique, nodeFindMany, nodeUpdateMany, migrationCreate, lineUpdate, projectionCreate, migrationNodeUpdate, externalJobCreate, auditCreate, transaction }; });
vi.mock('@ipeasy/db', () => ({ prisma: { $transaction: db.transaction } }));
import { CreateDedicatedLineMigrationUseCase } from './create-migration.use-case';
const ctx: AuthenticatedContext = { ownerId: 'admin-1', ownerType: 'PLATFORM_ADMIN', siteId: 'site-1', tenantId: null, scopes: [], requestId: 'req-1' };
beforeEach(() => { vi.clearAllMocks(); const key = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef'; db.lineFindFirst.mockResolvedValue({ id: 'line-1', tenantId: 'tenant-1', userId: 'user-1', desiredVersion: 1, countryCode: 'HK', clientEmail: 'line@example.com', clientIdentityCiphertext: encryptAesGcm(JSON.stringify({ id: 'client-1' }), key), protocol: 'VLESS', quotaBytes: null, uplinkLimitBps: null, downlinkLimitBps: null, maxConnections: null, ipLimit: null, expiresAt: null, inboundProfile: { inboundTag: 'sv' }, activeMigration: null, placement: { id: 'placement-1', targetReplicaCount: 2, policyId: 'policy-1', nodes: [{ nodeId: 'node-a' }, { nodeId: 'node-b' }] }, exitAssignment: { residentialExitId: 'exit-a', residentialExit: { id: 'exit-a', endpointCiphertext: encryptAesGcm(JSON.stringify({ host: '203.0.113.9', port: 1080 }), key), credentialCiphertext: encryptAesGcm(JSON.stringify({ username: 'u', password: 'p' }), key) } } }); db.migrationFindUnique.mockResolvedValue(null); db.policyFindUnique.mockResolvedValue({ id: 'policy-1', maxUnitsPerNode: 10, allowedNodes: [{ nodeId: 'node-a' }, { nodeId: 'node-b' }, { nodeId: 'node-c' }, { nodeId: 'node-d' }] }); db.nodeFindMany.mockResolvedValue([{ id: 'node-c', capacityUnits: 10, allocatedUnits: 0 }, { id: 'node-d', capacityUnits: 10, allocatedUnits: 0 }]); db.nodeUpdateMany.mockResolvedValue({ count: 1 }); db.migrationCreate.mockResolvedValue({ id: 'migration-1', dedicatedLineId: 'line-1', type: 'NODE_ONLY', phase: 'PREPARE', status: 'ACTIVE', sourceExitId: 'exit-a', targetExitId: null, nodes: [{ nodeId: 'node-a', role: 'SOURCE' }, { nodeId: 'node-b', role: 'SOURCE' }, { nodeId: 'node-c', role: 'TARGET' }, { nodeId: 'node-d', role: 'TARGET' }] }); });
describe('CreateDedicatedLineMigrationUseCase', () => {
  const useCase = () => new CreateDedicatedLineMigrationUseCase({ get: () => '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef' } as never);
  it('creates NODE_ONLY migration and preserves current resources', async () => { const result = await useCase().execute(ctx, 'line-1', { type: 'NODE_ONLY', targetNodeIds: ['node-c', 'node-d'], reason: 'node incident', idempotencyKey: 'migration-1' }); expect(result).toMatchObject({ id: 'migration-1', phase: 'PREPARE', targetNodeIds: ['node-c', 'node-d'] }); expect(db.lineUpdate).toHaveBeenCalledWith({ where: { id: 'line-1' }, data: { activeMigrationId: 'migration-1' } }); });
  it('rejects a second active migration', async () => { db.lineFindFirst.mockResolvedValueOnce({ ...(await db.lineFindFirst()), activeMigration: { id: 'existing' } }); await expect(useCase().execute(ctx, 'line-1', { type: 'NODE_ONLY', targetNodeIds: ['node-c', 'node-d'], reason: 'again', idempotencyKey: 'migration-2' })).rejects.toMatchObject({ reasonKey: 'line_migration_already_active', httpStatus: 409 }); });
  it('replays the same idempotency key', async () => { db.migrationFindUnique.mockResolvedValueOnce({ id: 'migration-1', dedicatedLineId: 'line-1', type: 'NODE_ONLY', reason: 'node incident', phase: 'PREPARE', status: 'ACTIVE', sourceExitId: 'exit-a', targetExitId: null, nodes: [{ nodeId: 'node-a', role: 'SOURCE' }] }); await expect(useCase().execute(ctx, 'line-1', { type: 'NODE_ONLY', targetNodeIds: ['node-c', 'node-d'], reason: 'node incident', idempotencyKey: 'migration-1' })).resolves.toMatchObject({ id: 'migration-1' }); expect(db.nodeUpdateMany).not.toHaveBeenCalled(); });

  it('rejects retained target nodes because OpenUI cannot stage the same client twice on one node', async () => {
    await expect(useCase().execute(ctx, 'line-1', { type: 'NODE_ONLY', targetNodeIds: ['node-a', 'node-c'], reason: 'partial move', idempotencyKey: 'migration-retained' })).rejects.toMatchObject({
      reasonKey: 'migration_retained_node_staging_unsupported', httpStatus: 422,
    });
    expect(db.nodeUpdateMany).not.toHaveBeenCalled();
  });

  it('rejects EXIT_ONLY until the data plane supports staged egress replacement', async () => {
    await expect(useCase().execute(ctx, 'line-1', { type: 'EXIT_ONLY', targetExitId: 'exit-b', reason: 'exit move', idempotencyKey: 'migration-exit' })).rejects.toMatchObject({
      reasonKey: 'migration_exit_only_staging_unsupported', httpStatus: 422,
    });
    expect(db.nodeUpdateMany).not.toHaveBeenCalled();
  });
});
