import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodEnum<["development", "test", "production"]>;
    RELEASE_GIT_SHA: z.ZodDefault<z.ZodString>;
    PORT: z.ZodDefault<z.ZodNumber>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    APP_ENCRYPTION_KEY: z.ZodString;
    JWT_SECRET: z.ZodString;
    APP_PLATFORM_CURRENCY: z.ZodString;
    API_RATE_LIMIT_WINDOW_MS: z.ZodDefault<z.ZodNumber>;
    API_RATE_LIMIT_MAX_REQUESTS: z.ZodDefault<z.ZodNumber>;
    API_RATE_LIMIT_ORDER_MAX_REQUESTS: z.ZodDefault<z.ZodNumber>;
    API_BODY_LIMIT_BYTES: z.ZodDefault<z.ZodNumber>;
    OPENAPI_EXPOSURE_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    LEGACY_API_V1_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    LEGACY_API_SITE_ID: z.ZodDefault<z.ZodString>;
    LEGACY_STATIC_PROXY_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    ALLOW_PLACEHOLDER_APIKEYS: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    ALLOW_LOCAL_DEV_APIKEY: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    PAYMENT_CONFIRMATION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    PROVIDER_FULFILLMENT_EXECUTION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    PROVIDER_FULFILLMENT_PROVIDER_ALLOWLIST: z.ZodDefault<z.ZodString>;
    PROVIDER_FULFILLMENT_UPSTREAM_ACCOUNT_ALLOWLIST: z.ZodDefault<z.ZodString>;
    DEDICATED_LINE_ORDER_EXECUTION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    DEDICATED_LINE_ORDER_PROVIDER_ALLOWLIST: z.ZodDefault<z.ZodString>;
    DEDICATED_LINE_ORDER_ACCOUNT_ALLOWLIST: z.ZodDefault<z.ZodString>;
    DEDICATED_LINE_PROJECTION_EXECUTION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    DEDICATED_LINE_MIGRATION_EXECUTION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    DEDICATED_LINE_HEALTH_EXECUTION_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    BARK_ALERTS_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    BARK_SERVER_URL: z.ZodDefault<z.ZodString>;
    BARK_DEVICE_KEYS: z.ZodDefault<z.ZodString>;
    BARK_REQUEST_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    PROVIDER_INVENTORY_SYNC_ENABLED: z.ZodDefault<z.ZodEnum<["true", "false"]>>;
    DATABASE_INVENTORY_FRESHNESS_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_FULFILLMENT_POLL_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_FULFILLMENT_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_ORDER_POLL_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_ORDER_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    CONTROL_NODE_REQUEST_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_PROJECTION_POLL_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_PROJECTION_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_MIGRATION_POLL_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_MIGRATION_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    WORKER_BARK_OUTBOX_POLL_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_BARK_OUTBOX_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_BATCH_SIZE: z.ZodDefault<z.ZodNumber>;
    WORKER_INVENTORY_SYNC_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    PROXY_CHECK_TARGET_URL: z.ZodDefault<z.ZodString>;
    PROXY_CHECK_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    DEDICATED_LINE_MIGRATION_SMOKE_TARGET_URL: z.ZodDefault<z.ZodString>;
    DEDICATED_LINE_MIGRATION_SMOKE_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    SCHEMA_DIAGNOSTIC_TOKEN: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    RELEASE_GIT_SHA: string;
    PORT: number;
    DATABASE_URL: string;
    REDIS_URL: string;
    APP_ENCRYPTION_KEY: string;
    JWT_SECRET: string;
    APP_PLATFORM_CURRENCY: string;
    API_RATE_LIMIT_WINDOW_MS: number;
    API_RATE_LIMIT_MAX_REQUESTS: number;
    API_RATE_LIMIT_ORDER_MAX_REQUESTS: number;
    API_BODY_LIMIT_BYTES: number;
    OPENAPI_EXPOSURE_ENABLED: "true" | "false";
    CORS_ORIGINS: string;
    LEGACY_API_V1_ENABLED: "true" | "false";
    LEGACY_API_SITE_ID: string;
    LEGACY_STATIC_PROXY_ENABLED: "true" | "false";
    ALLOW_PLACEHOLDER_APIKEYS: "true" | "false";
    ALLOW_LOCAL_DEV_APIKEY: "true" | "false";
    PAYMENT_CONFIRMATION_ENABLED: "true" | "false";
    PROVIDER_FULFILLMENT_EXECUTION_ENABLED: "true" | "false";
    PROVIDER_FULFILLMENT_PROVIDER_ALLOWLIST: string;
    PROVIDER_FULFILLMENT_UPSTREAM_ACCOUNT_ALLOWLIST: string;
    DEDICATED_LINE_ORDER_EXECUTION_ENABLED: "true" | "false";
    DEDICATED_LINE_ORDER_PROVIDER_ALLOWLIST: string;
    DEDICATED_LINE_ORDER_ACCOUNT_ALLOWLIST: string;
    DEDICATED_LINE_PROJECTION_EXECUTION_ENABLED: "true" | "false";
    DEDICATED_LINE_MIGRATION_EXECUTION_ENABLED: "true" | "false";
    DEDICATED_LINE_HEALTH_EXECUTION_ENABLED: "true" | "false";
    BARK_ALERTS_ENABLED: "true" | "false";
    BARK_SERVER_URL: string;
    BARK_DEVICE_KEYS: string;
    BARK_REQUEST_TIMEOUT_MS: number;
    PROVIDER_INVENTORY_SYNC_ENABLED: "true" | "false";
    DATABASE_INVENTORY_FRESHNESS_MS: number;
    WORKER_FULFILLMENT_POLL_INTERVAL_MS: number;
    WORKER_FULFILLMENT_BATCH_SIZE: number;
    WORKER_DEDICATED_LINE_ORDER_POLL_INTERVAL_MS: number;
    WORKER_DEDICATED_LINE_ORDER_BATCH_SIZE: number;
    CONTROL_NODE_REQUEST_TIMEOUT_MS: number;
    WORKER_DEDICATED_LINE_PROJECTION_POLL_INTERVAL_MS: number;
    WORKER_DEDICATED_LINE_PROJECTION_BATCH_SIZE: number;
    WORKER_DEDICATED_LINE_MIGRATION_POLL_INTERVAL_MS: number;
    WORKER_DEDICATED_LINE_MIGRATION_BATCH_SIZE: number;
    WORKER_BARK_OUTBOX_POLL_INTERVAL_MS: number;
    WORKER_BARK_OUTBOX_BATCH_SIZE: number;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_INTERVAL_MS: number;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_BATCH_SIZE: number;
    WORKER_INVENTORY_SYNC_INTERVAL_MS: number;
    PROXY_CHECK_TARGET_URL: string;
    PROXY_CHECK_TIMEOUT_MS: number;
    DEDICATED_LINE_MIGRATION_SMOKE_TARGET_URL: string;
    DEDICATED_LINE_MIGRATION_SMOKE_TIMEOUT_MS: number;
    SCHEMA_DIAGNOSTIC_TOKEN: string;
}, {
    NODE_ENV: "development" | "test" | "production";
    DATABASE_URL: string;
    REDIS_URL: string;
    APP_ENCRYPTION_KEY: string;
    JWT_SECRET: string;
    APP_PLATFORM_CURRENCY: string;
    RELEASE_GIT_SHA?: string | undefined;
    PORT?: number | undefined;
    API_RATE_LIMIT_WINDOW_MS?: number | undefined;
    API_RATE_LIMIT_MAX_REQUESTS?: number | undefined;
    API_RATE_LIMIT_ORDER_MAX_REQUESTS?: number | undefined;
    API_BODY_LIMIT_BYTES?: number | undefined;
    OPENAPI_EXPOSURE_ENABLED?: "true" | "false" | undefined;
    CORS_ORIGINS?: string | undefined;
    LEGACY_API_V1_ENABLED?: "true" | "false" | undefined;
    LEGACY_API_SITE_ID?: string | undefined;
    LEGACY_STATIC_PROXY_ENABLED?: "true" | "false" | undefined;
    ALLOW_PLACEHOLDER_APIKEYS?: "true" | "false" | undefined;
    ALLOW_LOCAL_DEV_APIKEY?: "true" | "false" | undefined;
    PAYMENT_CONFIRMATION_ENABLED?: "true" | "false" | undefined;
    PROVIDER_FULFILLMENT_EXECUTION_ENABLED?: "true" | "false" | undefined;
    PROVIDER_FULFILLMENT_PROVIDER_ALLOWLIST?: string | undefined;
    PROVIDER_FULFILLMENT_UPSTREAM_ACCOUNT_ALLOWLIST?: string | undefined;
    DEDICATED_LINE_ORDER_EXECUTION_ENABLED?: "true" | "false" | undefined;
    DEDICATED_LINE_ORDER_PROVIDER_ALLOWLIST?: string | undefined;
    DEDICATED_LINE_ORDER_ACCOUNT_ALLOWLIST?: string | undefined;
    DEDICATED_LINE_PROJECTION_EXECUTION_ENABLED?: "true" | "false" | undefined;
    DEDICATED_LINE_MIGRATION_EXECUTION_ENABLED?: "true" | "false" | undefined;
    DEDICATED_LINE_HEALTH_EXECUTION_ENABLED?: "true" | "false" | undefined;
    BARK_ALERTS_ENABLED?: "true" | "false" | undefined;
    BARK_SERVER_URL?: string | undefined;
    BARK_DEVICE_KEYS?: string | undefined;
    BARK_REQUEST_TIMEOUT_MS?: number | undefined;
    PROVIDER_INVENTORY_SYNC_ENABLED?: "true" | "false" | undefined;
    DATABASE_INVENTORY_FRESHNESS_MS?: number | undefined;
    WORKER_FULFILLMENT_POLL_INTERVAL_MS?: number | undefined;
    WORKER_FULFILLMENT_BATCH_SIZE?: number | undefined;
    WORKER_DEDICATED_LINE_ORDER_POLL_INTERVAL_MS?: number | undefined;
    WORKER_DEDICATED_LINE_ORDER_BATCH_SIZE?: number | undefined;
    CONTROL_NODE_REQUEST_TIMEOUT_MS?: number | undefined;
    WORKER_DEDICATED_LINE_PROJECTION_POLL_INTERVAL_MS?: number | undefined;
    WORKER_DEDICATED_LINE_PROJECTION_BATCH_SIZE?: number | undefined;
    WORKER_DEDICATED_LINE_MIGRATION_POLL_INTERVAL_MS?: number | undefined;
    WORKER_DEDICATED_LINE_MIGRATION_BATCH_SIZE?: number | undefined;
    WORKER_BARK_OUTBOX_POLL_INTERVAL_MS?: number | undefined;
    WORKER_BARK_OUTBOX_BATCH_SIZE?: number | undefined;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_INTERVAL_MS?: number | undefined;
    WORKER_DEDICATED_LINE_RESERVATION_RECLAIM_BATCH_SIZE?: number | undefined;
    WORKER_INVENTORY_SYNC_INTERVAL_MS?: number | undefined;
    PROXY_CHECK_TARGET_URL?: string | undefined;
    PROXY_CHECK_TIMEOUT_MS?: number | undefined;
    DEDICATED_LINE_MIGRATION_SMOKE_TARGET_URL?: string | undefined;
    DEDICATED_LINE_MIGRATION_SMOKE_TIMEOUT_MS?: number | undefined;
    SCHEMA_DIAGNOSTIC_TOKEN?: string | undefined;
}>;
export type EnvConfig = z.infer<typeof envSchema>;
export declare const env: EnvConfig;
export {};
