"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = void 0;
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["AUTH_REQUIRED"] = "AUTH_REQUIRED";
    ErrorCode["PERMISSION_DENIED"] = "PERMISSION_DENIED";
    ErrorCode["TENANT_SCOPE_VIOLATION"] = "TENANT_SCOPE_VIOLATION";
    ErrorCode["VALIDATION_ERROR"] = "VALIDATION_ERROR";
    ErrorCode["IDEMPOTENCY_CONFLICT"] = "IDEMPOTENCY_CONFLICT";
    ErrorCode["WALLET_INSUFFICIENT_BALANCE"] = "WALLET_INSUFFICIENT_BALANCE";
    ErrorCode["CURRENCY_NOT_SUPPORTED"] = "CURRENCY_NOT_SUPPORTED";
    ErrorCode["RESOURCE_MAPPING_MISSING"] = "RESOURCE_MAPPING_MISSING";
    ErrorCode["PRICE_MISSING"] = "PRICE_MISSING";
    ErrorCode["PRODUCT_DISABLED"] = "PRODUCT_DISABLED";
    ErrorCode["UPSTREAM_DISABLED"] = "UPSTREAM_DISABLED";
    ErrorCode["UPSTREAM_ERROR"] = "UPSTREAM_ERROR";
    ErrorCode["UPSTREAM_TIMEOUT"] = "UPSTREAM_TIMEOUT";
    ErrorCode["UPSTREAM_OUT_OF_STOCK"] = "UPSTREAM_OUT_OF_STOCK";
    ErrorCode["CONTROL_NODE_CONFIG_INVALID"] = "CONTROL_NODE_CONFIG_INVALID";
    ErrorCode["DEDICATED_LINE_CONFIG_INVALID"] = "DEDICATED_LINE_CONFIG_INVALID";
    ErrorCode["CONTROL_NODE_CAPACITY_EXHAUSTED"] = "CONTROL_NODE_CAPACITY_EXHAUSTED";
    ErrorCode["UNSUPPORTED_CAPABILITY"] = "UNSUPPORTED_CAPABILITY";
    ErrorCode["INTERNAL_ERROR"] = "INTERNAL_ERROR";
    ErrorCode["NOT_FOUND"] = "NOT_FOUND";
})(ErrorCode || (exports.ErrorCode = ErrorCode = {}));
//# sourceMappingURL=error-codes.js.map